services:
  rustapp:
    container_name: rustapp
    image: nick/rustapp:latest
    build:
      context: ./backend
      dockerfile: rust.dockerfile
      args:
        DATABASE_URL: postgres://nick:Ybrbnf2024714!@db:5432/nias_postres
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: nick
      POSTGRES_PASSWORD: Ybrbnf2024714!
      POSTGRES_DB: nias_postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}